// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/podpulse/v1/incident.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncidentReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	IncidentType  string                 `protobuf:"bytes,2,opt,name=incident_type,json=incidentType,proto3" json:"incident_type,omitempty"` // e.g. OOMKilled, CrashLoopBackOff
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	RestartCount  int32                  `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	RawContext    string                 `protobuf:"bytes,7,opt,name=raw_context,json=rawContext,proto3" json:"raw_context,omitempty"`  // JSON-serialized, size-bounded
	DetectedAt    int64                  `protobuf:"varint,8,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"` // Unix timestamp (UTC)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentReport) Reset() {
	*x = IncidentReport{}
	mi := &file_proto_podpulse_v1_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentReport) ProtoMessage() {}

func (x *IncidentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_podpulse_v1_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentReport.ProtoReflect.Descriptor instead.
func (*IncidentReport) Descriptor() ([]byte, []int) {
	return file_proto_podpulse_v1_incident_proto_rawDescGZIP(), []int{0}
}

func (x *IncidentReport) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IncidentReport) GetIncidentType() string {
	if x != nil {
		return x.IncidentType
	}
	return ""
}

func (x *IncidentReport) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IncidentReport) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *IncidentReport) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *IncidentReport) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *IncidentReport) GetRawContext() string {
	if x != nil {
		return x.RawContext
	}
	return ""
}

func (x *IncidentReport) GetDetectedAt() int64 {
	if x != nil {
		return x.DetectedAt
	}
	return 0
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_proto_podpulse_v1_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_podpulse_v1_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_proto_podpulse_v1_incident_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAck) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *ReportAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_podpulse_v1_incident_proto protoreflect.FileDescriptor

const file_proto_podpulse_v1_incident_proto_rawDesc = "" +
	"\n" +
	" proto/podpulse/v1/incident.proto\x12\vpodpulse.v1\"\x93\x02\n" +
	"\x0eIncidentReport\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12#\n" +
	"\rincident_type\x18\x02 \x01(\tR\fincidentType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\x12\x1f\n" +
	"\vraw_context\x18\a \x01(\tR\n" +
	"rawContext\x12\x1f\n" +
	"\vdetected_at\x18\b \x01(\x03R\n" +
	"detectedAt\"H\n" +
	"\tReportAck\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted2X\n" +
	"\x0fIncidentService\x12E\n" +
	"\x0eReportIncident\x12\x1b.podpulse.v1.IncidentReport\x1a\x16.podpulse.v1.ReportAckB9Z7github.com/podpulse/podpulse-agent/proto/podpulse/v1;v1b\x06proto3"

var (
	file_proto_podpulse_v1_incident_proto_rawDescOnce sync.Once
	file_proto_podpulse_v1_incident_proto_rawDescData []byte
)

func file_proto_podpulse_v1_incident_proto_rawDescGZIP() []byte {
	file_proto_podpulse_v1_incident_proto_rawDescOnce.Do(func() {
		file_proto_podpulse_v1_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_podpulse_v1_incident_proto_rawDesc), len(file_proto_podpulse_v1_incident_proto_rawDesc)))
	})
	return file_proto_podpulse_v1_incident_proto_rawDescData
}

var file_proto_podpulse_v1_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_podpulse_v1_incident_proto_goTypes = []any{
	(*IncidentReport)(nil), // 0: podpulse.v1.IncidentReport
	(*ReportAck)(nil),      // 1: podpulse.v1.ReportAck
}
var file_proto_podpulse_v1_incident_proto_depIdxs = []int32{
	0, // 0: podpulse.v1.IncidentService.ReportIncident:input_type -> podpulse.v1.IncidentReport
	1, // 1: podpulse.v1.IncidentService.ReportIncident:output_type -> podpulse.v1.ReportAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_podpulse_v1_incident_proto_init() }
func file_proto_podpulse_v1_incident_proto_init() {
	if File_proto_podpulse_v1_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_podpulse_v1_incident_proto_rawDesc), len(file_proto_podpulse_v1_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_podpulse_v1_incident_proto_goTypes,
		DependencyIndexes: file_proto_podpulse_v1_incident_proto_depIdxs,
		MessageInfos:      file_proto_podpulse_v1_incident_proto_msgTypes,
	}.Build()
	File_proto_podpulse_v1_incident_proto = out.File
	file_proto_podpulse_v1_incident_proto_goTypes = nil
	file_proto_podpulse_v1_incident_proto_depIdxs = nil
}
